name: CD

on: 
#   push:
#     branches:
#       - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - uses: actions/setup-python@v2

      # - name: act 
        # # if: ${{ env.ACT }} # this's on the master only
        # run: |
          # apt update -y
          # apt install -y sudo python3 python3-pip

      - name: Build
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          pip3 install graph-cli
          sudo apt update -y
          sudo apt install -y jq
          bash ./collect_data.sh 65
          bash ./build.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update
          commit_options: '--amend'
          push_options: '--force'  
